# Generated by Django 4.1.5 on 2023-01-24 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteREST', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('text', models.TextField(blank=True, max_length=300, null=True)),
                ('author', models.CharField(blank=True, max_length=250, null=True)),
                ('work_space', models.CharField(blank=True, max_length=250, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
