# Generated by Django 4.1.5 on 2023-01-31 00:52

import SiteREST.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteREST', '0002_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='status',
            field=models.CharField(choices=[('draft', 'DRAFT'), ('public', 'PUBLIC')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'DRAFT'), ('public', 'PUBLIC')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='pictures',
            field=models.ImageField(default='posts/My_img.jpg', upload_to=SiteREST.models.upload_to, verbose_name='Image'),
        ),
    ]
