# Generated by Django 4.1.5 on 2023-01-31 05:04

import SiteREST.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteREST', '0004_alter_blogpost_pictures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='pictures',
            field=models.ImageField(default='posts/My_img.jpg', upload_to=SiteREST.models.upload_blog_to, verbose_name='Image'),
        ),
    ]
