# Generated by Django 4.1.5 on 2023-02-03 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteREST', '0005_alter_blogpost_pictures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='text',
            field=models.TextField(default='text', max_length=600),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(default='title', max_length=250),
        ),
    ]
