# Generated by Django 4.1.5 on 2023-03-03 03:51

import SiteREST.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteREST', '0006_alter_blogpost_text_alter_blogpost_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgtype', models.CharField(blank=True, max_length=250, null=True)),
                ('img', models.ImageField(default='posts/My_img.jpg', upload_to=SiteREST.models.upload_bgimg_to, verbose_name='Image')),
            ],
        ),
    ]
